-- GENERATED by scripts/gen-catalogue-seed.mjs from src/data/{events,bundles}.js.
-- Do not hand-edit: regenerate with `node scripts/gen-catalogue-seed.mjs --sql-file`,
-- so the database and the site cannot drift apart. Re-running is safe.

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
insert into public.event_catalogue
  (id, number, title, category, mode, realm, tagline, about, event_date, venue,
   team_size, max_size, status, accent, sigil, link_key, sort_order)
values
    ('nexus-breach', '01', $n$NEXUS BREACH$n$, 'HACKATHON', null, 'forge', $n$Break the boundaries.
Build beyond them.$n$,
     array[$n$Organised to encourage participants to develop efficient resource-management solutions addressing real-world problems — teams take on a live challenge and ship a working prototype before the final evaluation.$n$, $n$Sessions: Oct 5, 11:00 AM – 12:30 PM (first session) and 1:30 PM – 4:00 PM (second session); Oct 6, 9:30 AM – 11:00 AM (final session & evaluation, followed by the valedictory). Participants must bring their own laptops and chargers, and an RJ45 connector if required.$n$]::text[],
     $n$OCT 5 — 6, 2026$n$, $n$E-BLOCK · LABS A–E · SEMINAR HALL$n$, $n$2 — 5 MEMBERS$n$,
     '5', $n$REGISTRATION OPEN$n$, 'violet', 'fracture', 'nexusBreach', 0),
    ('vision-2065', '02', $n$VISION 2065$n$, 'IDEATHON', null, 'forge', $n$Imagine the future.
Engineer the impossible.$n$,
     array[$n$Participants develop presentations on efficient resource management addressing real-world problems — pitch the vision of 2065 to a live jury.$n$, $n$Oct 5, 1:30 PM – 4:00 PM. Advance registration required; participants must bring their own laptops and chargers. Auditorium facilities with high-speed Wi-Fi, power supply and projector/presentation setup.$n$]::text[],
     $n$OCT 5, 2026$n$, $n$CLASS ROOMS$n$, $n$1 — 5 MEMBERS$n$,
     '5', $n$REGISTRATION OPEN$n$, 'gold', 'temporal', 'vision2065', 1),
    ('circuits-of-nexus', '03', $n$CIRCUITS OF NEXUS$n$, 'CIRCUIT EXPO', null, 'forge', $n$Where ideas
become machines.$n$,
     array[$n$Participants develop systems on efficient resource management addressing real-world problems and exhibit them live — every stall powered on, running and open to interrogation.$n$, $n$Oct 7 — arrangements 11:00 AM – 12:30 PM, the Expo 1:30 PM – 4:00 PM. Advance registration required; bring your own materials and circuits. Dedicated display tables, power supply, electrical safety arrangements and exhibition space provided at the Main Block ground floor.$n$]::text[],
     $n$OCT 7, 2026$n$, $n$MAIN BLOCK — GROUND FLOOR$n$, $n$1 — 5 MEMBERS$n$,
     '5', $n$REGISTRATION OPEN$n$, 'violet', 'circuit', 'circuitsOfNexus', 2),
    ('ai-turing-gambit', '04', $n$AI TURING GAMBIT$n$, 'MANIPULATING THE AI', null, 'forge', $n$Don't ask what AI can do.
Ask what you can make it do.$n$,
     array[$n$Challenge the NEXUS AI itself: communicate strategically, explore its responses and extract resource-related information through problem-solving — a duel of instruction, patience and cunning with machine intelligence.$n$, $n$Oct 6, 10:00 AM – 12:30 PM at the Main Block. Advance registration required; participants must bring their own laptops and chargers.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$MAIN BLOCK — 2 CLASSROOMS$n$, $n$1 — 5 MEMBERS$n$,
     '5', $n$REGISTRATION OPEN$n$, 'violet', 'neural', 'aiTuringGambit', 3),
    ('code-rebuilding', '05', $n$CODE REBUILDING$n$, 'CODE CRACK', null, 'forge', $n$The code is broken.
Can you reconstruct it?$n$,
     array[$n$Analyse and reconstruct corrupted code, identify logical errors and develop efficient solutions for managing resources within the NEXUS system.$n$, $n$Oct 6, 1:30 PM – 3:00 PM (event session) in Labs D & E. Bring laptops — speed and precision both count.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$LABS D & E$n$, $n$1 — 5 MEMBERS$n$,
     '5', $n$REGISTRATION OPEN$n$, 'lavender', 'rebuild', 'codeRebuilding', 4),
    ('the-scientist-files', '01', $n$THE SCIENTIST FILES$n$, 'MURDER MYSTERY', null, 'paradox', $n$Every clue matters.
Every suspect has a secret.$n$,
     array[$n$A story-driven murder-mystery investigation built to sharpen critical thinking, analytical reasoning, observation, teamwork and problem-solving.$n$, $n$Oct 6, 10:00 AM – 12:30 PM across the college premises. Teams receive three fictional case files and must investigate all three, submitting a final report with evidence analysis, deductions, timeline and conclusion. Judging rewards evidence-based reasoning, scientific analysis, accuracy and clarity.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$COLLEGE PREMISES$n$, $n$2 — 4 MEMBERS$n$,
     '4', $n$REGISTRATION OPEN$n$, 'gold', 'mystery', 'scientistFiles', 5),
    ('paradox-2065', '02', $n$PARADOX 2065$n$, 'FUTURE-BASED THINKING CHALLENGE', null, 'paradox', $n$What happens when
tomorrow becomes today?$n$,
     array[$n$Futuristic "What If?" scenarios set in 2065 around resource management, technology and society — respond with creative, logical and detailed answers that defend every conclusion.$n$, $n$Oct 6, 10:00 AM – 12:30 PM in the E-block classroom. Answers must be completed within the allotted time with clear reasoning; judging focuses on originality, logical thinking, depth, creativity and futuristic vision.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$E-BLOCK CLASSROOM$n$, $n$SOLO$n$,
     'individual', $n$REGISTRATION OPEN$n$, 'violet', 'timeline', 'paradox2065', 6),
    ('shutter-quest', '03', $n$SHUTTER QUEST$n$, 'SPOT PHOTOGRAPHY', null, 'paradox', $n$One moment.
One frame. One story.$n$,
     array[$n$Capture the energy, creativity and unforgettable moments of NEXUS'65 while building visual-storytelling and observation skills — one frame at the event venue that interprets the theme 2065.$n$, $n$Oct 6, 11:00 AM – 3:30 PM. Bring your own smartphone or camera; photographs must be original and taken during the allotted window (no AI-generated or pre-shot entries), with consent before shooting identifiable people. Judging weighs composition, creativity, storytelling, technical quality and interpretation of the theme.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$NEXUS OFF-GRID — CITY SECTORS$n$, $n$SOLO$n$,
     'individual', $n$REGISTRATION OPEN$n$, 'lavender', 'lens', 'shutterQuest', 7),
    ('matrix', '04', $n$MATRIX$n$, 'MEME MAKING', null, 'paradox', $n$Enter the matrix.
Break reality.$n$,
     array[$n$Express creativity, humour and awareness through original memes that explore the future of 2065, resource management and real-world challenges — relatable, engaging and on-theme.$n$, $n$Oct 6, 10:00 AM – 12:30 PM. Bring a laptop or smartphone; memes must be original, created within the allotted time and suitable for a college audience. Judging focuses on humour, creativity, originality and futuristic relevance.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$NEXUS OFF-GRID — GLITCH DECK$n$, $n$SOLO$n$,
     'individual', $n$REGISTRATION OPEN$n$, 'violet', 'matrix', 'matrix', 8),
    ('pixel-resistance', '05', $n$PIXEL RESISTANCE$n$, 'POSTER DESIGN', null, 'paradox', $n$Create what cannot
be ignored.$n$,
     array[$n$Design original, visually impactful posters that promote awareness of resource management and inspire positive change — representing life, technology, society or challenges of the year 2065.$n$, $n$Oct 6, 10:00 AM – 12:30 PM in two Main Block classrooms. Bring laptops and chargers; posters must be created during the competition with no plagiarism or pre-made work. Judging rewards creativity, concept, visual appeal and relevance to 2065.$n$]::text[],
     $n$OCT 6, 2026$n$, $n$MAIN BLOCK — 2 CLASSROOMS$n$, $n$SOLO$n$,
     'individual', $n$REGISTRATION OPEN$n$, 'gold', 'pixel', 'pixelResistance', 9),
    ('free-fire', 'GAME 01', $n$FREE FIRE$n$, 'ESPORTS', 'SQUAD BATTLE ROYALE', 'arena', $n$Drop in.
Only one squad survives.$n$,
     array[$n$Esports promotes teamwork, strategic thinking, healthy competition, and a positive sense of community among engineering students.$n$, $n$Free Fire is the Arena's only title this season — squad up in fours, check in before the first drop and battle after college hours until one team owns the island.$n$]::text[],
     $n$OCT 5 — 6, 2026 · AFTER COLLEGE HOURS$n$, $n$THE ARENA — MAIN STAGE$n$, $n$SQUAD OF 4$n$,
     '4', $n$REGISTRATION OPEN$n$, 'violet', 'squad', 'freeFire', 10)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- bundles
-- ---------------------------------------------------------------------------
-- Bundles are inserted RETIRED and activated at the end, in one statement.
--
-- The order is forced by the schema: an ACTIVE bundle must have a non-empty
-- content_key (the CHECK from migration section 2), but content_key is computed
-- by the trigger that fires when the include lines land. So the parents go in
-- inactive, the lines go in, the trigger fills each key, and only then does the
-- final UPDATE publish them. Activating inline in the VALUES list is the obvious
-- thing to write and it fails the CHECK on the very first bundle.

-- Which bundles did THIS run actually insert? Captured in a temp table rather
-- than inferred, because the publish step below must not touch anything else.
--
-- The bug this replaces: the publish was
--     where bc.is_active = false and bc.content_key <> '' and exists (include)
-- which reads like a seed-scoped update but is not scoped to the seed AT ALL.
-- Re-running the migration after a master had deliberately retired a seeded
-- bundle would flip it back on: the row is inactive, has a content key and has
-- include lines, so it satisfies every clause — the retirement is silently
-- undone, and the bundle reappears on the public site. ON CONFLICT DO NOTHING
-- protects the INSERT; nothing protected the UPDATE.
create temporary table nexus_seed_publish (id text primary key) on commit drop;

with seeded as (
  insert into public.bundle_catalogue
    (id, number, name, group_id, kicker, title_lines, sort_order, is_active, content_key)
  values
    ('bundled-299', '01', $n$BUNDLED$n$, 'nexus-forge', $n$Payment bundles · 01 — 06$n$, array[$n$NEXUS$n$, $n$REBUILDERS BUNDLED$n$]::text[], 0, false, ''),
    ('bundled-349', '02', $n$BUNDLED$n$, 'nexus-forge', $n$Payment bundles · 01 — 06$n$, array[$n$NEXUS$n$, $n$REBUILDERS BUNDLED$n$]::text[], 1, false, ''),
    ('forge-bundled-349', '03', $n$NEXUS REBUILDERS BUNDLED$n$, 'nexus-forge', $n$Payment bundles · 01 — 06$n$, array[$n$NEXUS$n$, $n$REBUILDERS BUNDLED$n$]::text[], 2, false, ''),
    ('forge-bundled-399', '04', $n$NEXUS REBUILDERS BUNDLED$n$, 'nexus-forge', $n$Payment bundles · 01 — 06$n$, array[$n$NEXUS$n$, $n$REBUILDERS BUNDLED$n$]::text[], 3, false, ''),
    ('bundled-399', '05', $n$BUNDLED$n$, 'nexus-forge', $n$Payment bundles · 01 — 06$n$, array[$n$NEXUS$n$, $n$REBUILDERS BUNDLED$n$]::text[], 4, false, ''),
    ('forge-paradox-bundled-399', '06', $n$NEXUS REBUILDERS BUNDLED$n$, 'nexus-forge', $n$Payment bundles · 01 — 06$n$, array[$n$NEXUS$n$, $n$REBUILDERS BUNDLED$n$]::text[], 5, false, ''),
    ('paradox-bundled-249', '07', $n$NEXUS OFF-GRID BUNDLED$n$, 'paradox', $n$Payment bundles · 07 — 08$n$, array[$n$NEXUS$n$, $n$OFF-GRID BUNDLED$n$]::text[], 6, false, ''),
    ('paradox-bundled-349', '08', $n$NEXUS OFF-GRID BUNDLED$n$, 'paradox', $n$Payment bundles · 07 — 08$n$, array[$n$NEXUS$n$, $n$OFF-GRID BUNDLED$n$]::text[], 7, false, '')
  on conflict (id) do nothing
  returning id
)
insert into nexus_seed_publish (id) select id from seeded;

insert into public.bundle_includes
  (bundle_id, position, event_id, pick_realm, pick_count, exclude_hackathon)
values
    ('bundled-299', 0, 'nexus-breach', null, null, false),
    ('bundled-299', 1, null, 'paradox', 1, false),
    ('bundled-349', 0, 'nexus-breach', null, null, false),
    ('bundled-349', 1, null, 'paradox', 2, false),
    ('forge-bundled-349', 0, 'nexus-breach', null, null, false),
    ('forge-bundled-349', 1, null, 'forge', 1, true),
    ('forge-bundled-399', 0, 'nexus-breach', null, null, false),
    ('forge-bundled-399', 1, null, 'forge', 2, true),
    ('bundled-399', 0, null, 'forge', 2, true),
    ('bundled-399', 1, null, 'paradox', 3, false),
    ('forge-paradox-bundled-399', 0, 'nexus-breach', null, null, false),
    ('forge-paradox-bundled-399', 1, null, 'forge', 1, true),
    ('forge-paradox-bundled-399', 2, null, 'paradox', 2, false),
    ('paradox-bundled-249', 0, null, 'paradox', 2, false),
    ('paradox-bundled-349', 0, null, 'paradox', 3, false)
on conflict (bundle_id, position) do nothing;

-- Publish ONLY the rows this run inserted, and only once their lines have given
-- them a key. Both guards are load-bearing and neither replaces the other:
--   * the temp table is what stops a retired bundle being revived on a re-run;
--   * content_key/exists stop publishing a parent whose include lines did not
--     land, which would otherwise abort the whole migration on the CHECK.
update public.bundle_catalogue bc
   set is_active = true
 where bc.is_active = false
   and bc.content_key <> ''
   and exists (select 1 from public.bundle_includes bi where bi.bundle_id = bc.id)
   and bc.id in (select id from nexus_seed_publish);

-- public.pricing is the price authority and the console edits it, so this seed
-- only fills ABSENT rows. ON CONFLICT DO NOTHING is what stops a regenerated seed
-- from overwriting a price a master has since changed.
insert into public.pricing (kind, ref_id, price)
values
    ('bundle', 'bundled-299', 299),
    ('bundle', 'bundled-349', 349),
    ('bundle', 'forge-bundled-349', 349),
    ('bundle', 'forge-bundled-399', 399),
    ('bundle', 'bundled-399', 399),
    ('bundle', 'forge-paradox-bundled-399', 399),
    ('bundle', 'paradox-bundled-249', 249),
    ('bundle', 'paradox-bundled-349', 349)
on conflict (kind, ref_id) do nothing;

insert into public.pricing (kind, ref_id, price)
values
    ('event', 'nexus-breach', 349),
    ('event', 'vision-2065', 249),
    ('event', 'circuits-of-nexus', 249),
    ('event', 'ai-turing-gambit', 249),
    ('event', 'code-rebuilding', 249),
    ('event', 'the-scientist-files', 249),
    ('event', 'paradox-2065', 149),
    ('event', 'shutter-quest', 149),
    ('event', 'matrix', 149),
    ('event', 'pixel-resistance', 149),
    ('event', 'free-fire', 300)
on conflict (kind, ref_id) do nothing;
